version: '3.8'
name: 'english-ua'

services:
  backend:
    build:
      context: .
      dockerfile: Prebuilt.Dockerfile
    container_name: english-ua-backend
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - mongo
    links:
      - 'postgres:postgres'
      - 'mongo:mongo'
    environment:
      SPRING_PROFILES_ACTIVE: localDocker
    networks:
      - english-ua-network

  postgres:
    image: postgres
    container_name: english-ua-database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: english-ua
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - english-ua-database:/var/lib/postgresql/data
    networks:
      - english-ua-network

  mongo:
    image: mongo
    container_name: english-ua-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: english-ua
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - english-ua-mongodb:/data
    networks:
      - english-ua-network

#if "network english-ua-network declared as external, but could not be found"
#start script "docker network create english-ua-network"
networks:
  english-ua-network:
    external: true
    driver: bridge
    name: english-ua-network

volumes:
  #if "external volume "english-ua-database" not found"
  #start script "docker volume create english-ua-database"
  english-ua-database:
    external: true
    name: english-ua-database
  #if "external volume "english-ua-database" not found"
  #start script "docker volume create english-ua-mongodb"
  english-ua-mongodb:
    external: true
    name: english-ua-mongodb
