spring:
  flyway:
    enabled: false
    user: postgres
    password: postgres
    url: jdbc:postgresql://postgres:5432/english-ua
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres:5432/english-ua
  data:
    mongodb:
      host: mongo
      port: 27017
      username: root
      password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
